### ISSUE TITLE
Get projects with advisorID

### ISSUE THREAD

**Issue by zildj** [senior-design-marketplace/express-typescript-server#25]
**Description:** BadRequestError when filtering with an advisorId

**Verb:** Get

**Path:** `/projects/?advisorId=test`

**Response:** 400
{"type":"BadRequestError","message":"Malformed request"}

**Comment by mfreema1** [comment]
Was due to previous logic involving using uuids for user ids.  Thus, when you supply an id that does not conform to this, you get a bad request.  Will transfer validation to a string of range 1 to 64 characters.
