### ISSUE TITLE
Pagination of projects

### ISSUE THREAD

**Issue by zildj** [senior-design-marketplace/express-typescript-server#33]
**Description:** Pagination on GET on /projects

**Verb:** Get

**Path:** `/projects/?page=$(1...n)`

** Expected Response:** 
Array of 25 projects corresponding to the page or empty array if page number out of bounds
If query string not provided, default to first page

**Comment by mfreema1** [comment]
Added in b7d84461aad577f684b385fa39cf911645d2dd37
