### ISSUE TITLE
History event not created on image change

### ISSUE THREAD

**Issue by zildj** [senior-design-marketplace/express-typescript-server#39]
I'm not sure how you would fix this, but when an image is changed in S3, it does not create a history event on the project showing the change. For example, if a user changes the cover image stored in S3 (not the coverLink, since they can't), it does not create an event since it they did not hit the API directly. This occurs when editing the cover image and media board items on projects.
You could try to somehow patch it in to the API calls that return the pre-signed S3 urls, but then you run into the issue of knowing if the upload was successful...

**Comment by mfreema1** [comment]
This is a known problem.  Not every physical change to the project has an event hooked up to it for now -- only the simple ones.

For media handling, you need to somehow hook into the event loop inside of the media handler lambda.  Unfortunately, we do not yet have a service mesh of sorts and are instead relying on in-process event handling via the Node.js event loop.

Getting this mesh up and running is far beyond the scope of the current project.  We leave it to future teams to build upon if they deem this a necessary event.

**Comment by mfreema1** [comment]
To clarify, you would events to be distributed via some sort of event broker, such as Amazon SQS.  Since we are doing same-process event handling in the event loop, we cannot do this.
